language: node_js
services:
  - docker
node_js:
  - 8.2.1
cache:
  directories:
    - node_modules
    - server/node_modules
env:
  - NODE_ENV=production
install:
  - npm install --dev
script:
  - npm test
  - npm run build
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      cd server && npm install --production && cd ..;
      export REPO=martijnhols/wowanalyzer;
      export BRANCH=$(
         if [ "$TRAVIS_BRANCH" == "master" ]; then
           echo "latest";
         else
           echo $TRAVIS_BRANCH;
         fi | sed -r 's/\//-/g'
       );
      docker build --tag $REPO:$BRANCH --file Dockerfile.package .;
      docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
      docker push $REPO:$BRANCH;
    fi
