sudo: required
dist: trusty
language: node_js
services:
  - docker
node_js:
- '7'
cache:
  directories:
    - node_modules
    - server/node_modules
env:
  - NODE_ENV=production
install:
  - npm install --dev
script:
  - npm test
  - npm run build
after_success:
  - export REPO=martijnhols/wowanalyzer
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -f .dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO:$TAG
