version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wowanalyzer-dev
    environment:
      - NODE_ENV=development
    ports:
     - 3000:3000
     - 35729:35729
    volumes:
      - .:/usr/src/wowanalyzer
  webserver:
    build:
      context: .
      dockerfile: .dockerfile
    ports:
     - "3001:3000" # make it easier to run the dev server side-by-side
  database:
    image: "mariadb:10.3"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - '4306:3306' # don't conflict with existing MySQL servers
